### ISSUE TITLE
Feature Request: Include filesystem for snapshots

### ISSUE THREAD

**Issue by cf-sewe** [pdf/zfs_exporter#24]
I could not find a simple way to generate graphs per ZFS filesystem and their snapshot usage.

The metric currently looks like this:
```
zfs_dataset_logical_used_bytes{name="rpool/application@zrepl_20220407_154137_000",pool="rpool",type="snapshot"} 0
```

If we could add a `filesystem` label, we could build easy statistics of snapshots for each filesystem:

```
zfs_dataset_logical_used_bytes{name="zrepl_20220407_154137_000",filesystem="rpool/application",pool="rpool",type="snapshot"} 0
```

I think this would add a clear benefit, and also is consistent of how we handle `pool` for for example.

**Comment by lyz-code** [comment]
Hi @cf-sewe you can get the `filesystem` label if you configure the scraping in your prometheus configuration with relabeling:

```yaml
  - job_name: zfs_exporter
    metrics_path: /metrics
    static_configs:
    - targets: [192.168.3.236:9134] 
    metric_relabel_configs:
      - source_labels: ['name']
        regex: ^([^@]*).*$
        target_label: filesystem
        replacement: ${1}
      - source_labels: ['name']
        regex: ^.*:.._(.*)$
        target_label: snapshot_type
        replacement: ${1}
```
